os:
  - linux

language: c

install:
  - |
      git clone https://github.com/nim-lang/Nim.git
      cd Nim
      sh bootstrap.sh
      cd ..
before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/Nim/bin:$PATH

script:
  - cd tests
  - nim c -r tester
  - ./src/nimble install -y

notifications:
  irc: "chat.freenode.net#nimbuild"