on:
  push:
  pull_request:
  schedule:
  - cron: "0 19 * * *"

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        version:
          - devel
    name: ${{ matrix.os }} - ${{ matrix.nimversion }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nimversion }}
      - run: nim --version
      - name: Install Mercurial on macOS
        if: matrix.os == 'macos-latest'
        run: brew install mercurial
      - name: Run nim c -r tester
        run: |
          cd tests
          nim c -r --mm:refc tester
          # there's no need to add nimblepkg unit tests --
          # they are run by tmoduletests.nim
      - run: ./src/nimble install -y
